source 'https://cdn.cocoapods.org/'
#use_frameworks!
#use_modular_headers!

plugin 'cocoapods-mtxx-bin'
use_binaries!
#set_use_source_pods ['PodA']

platform :ios, '9.0'

target 'PodA_Example' do
#  pod 'PodA/MapKit', :path => '../'
  pod 'PodA', '0.1.3', :subspecs => ['Core', 'MapKit']
end
