source 'https://cdn.cocoapods.org/'
#use_frameworks!

plugin 'cocoapods-imy-bin'
use_binaries!
set_use_source_pods ['PodA']

platform :ios, '9.0'

target 'PodA_Example' do
#  pod 'PodA', :path => '../'
  pod 'PodA'
end
